//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTMWcfDealServiceTestApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QTMSession", Namespace="http://schemas.datacontract.org/2004/07/QTMWcfDealService.Contracts")]
    [System.SerializableAttribute()]
    public partial class QTMSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SwapDeal", Namespace="http://schemas.datacontract.org/2004/07/QTMWcfDealService.Contracts")]
    [System.SerializableAttribute()]
    public partial class SwapDeal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CounterpartyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DealDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime MaturityDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TickerNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Counterparty {
            get {
                return this.CounterpartyField;
            }
            set {
                if ((object.ReferenceEquals(this.CounterpartyField, value) != true)) {
                    this.CounterpartyField = value;
                    this.RaisePropertyChanged("Counterparty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DealDate {
            get {
                return this.DealDateField;
            }
            set {
                if ((this.DealDateField.Equals(value) != true)) {
                    this.DealDateField = value;
                    this.RaisePropertyChanged("DealDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Entity {
            get {
                return this.EntityField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityField, value) != true)) {
                    this.EntityField = value;
                    this.RaisePropertyChanged("Entity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MaturityDate {
            get {
                return this.MaturityDateField;
            }
            set {
                if ((this.MaturityDateField.Equals(value) != true)) {
                    this.MaturityDateField = value;
                    this.RaisePropertyChanged("MaturityDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TickerNumber {
            get {
                return this.TickerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TickerNumberField, value) != true)) {
                    this.TickerNumberField = value;
                    this.RaisePropertyChanged("TickerNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/QTMWcfDealService.Contracts")]
    [System.SerializableAttribute()]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private QTMWcfDealServiceTestApp.ServiceReference1.ResultStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QTMWcfDealServiceTestApp.ServiceReference1.ResultStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultStatus", Namespace="http://schemas.datacontract.org/2004/07/QTMWcfDealService.Enums")]
    public enum ResultStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customize", Namespace="http://schemas.datacontract.org/2004/07/QTMWcfDealService.Contracts")]
    [System.SerializableAttribute()]
    public partial class Customize : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Unwind", Namespace="http://schemas.datacontract.org/2004/07/QTMWcfDealService.Contracts")]
    [System.SerializableAttribute()]
    public partial class Unwind : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISwapDealService")]
    public interface ISwapDealService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwapDealService/LogOn", ReplyAction="http://tempuri.org/ISwapDealService/LogOnResponse")]
        QTMWcfDealServiceTestApp.ServiceReference1.QTMSession LogOn(string Username, string Password, string SiteName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwapDealService/LogOn", ReplyAction="http://tempuri.org/ISwapDealService/LogOnResponse")]
        System.Threading.Tasks.Task<QTMWcfDealServiceTestApp.ServiceReference1.QTMSession> LogOnAsync(string Username, string Password, string SiteName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwapDealService/InitializeSwapDeal", ReplyAction="http://tempuri.org/ISwapDealService/InitializeSwapDealResponse")]
        QTMWcfDealServiceTestApp.ServiceReference1.Result InitializeSwapDeal(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.SwapDeal objSwapDeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwapDealService/InitializeSwapDeal", ReplyAction="http://tempuri.org/ISwapDealService/InitializeSwapDealResponse")]
        System.Threading.Tasks.Task<QTMWcfDealServiceTestApp.ServiceReference1.Result> InitializeSwapDealAsync(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.SwapDeal objSwapDeal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwapDealService/CustomizeSwapDeal", ReplyAction="http://tempuri.org/ISwapDealService/CustomizeSwapDealResponse")]
        QTMWcfDealServiceTestApp.ServiceReference1.Result CustomizeSwapDeal(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.Customize objCustomize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwapDealService/CustomizeSwapDeal", ReplyAction="http://tempuri.org/ISwapDealService/CustomizeSwapDealResponse")]
        System.Threading.Tasks.Task<QTMWcfDealServiceTestApp.ServiceReference1.Result> CustomizeSwapDealAsync(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.Customize objCustomize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwapDealService/UnwindSwapDeal", ReplyAction="http://tempuri.org/ISwapDealService/UnwindSwapDealResponse")]
        QTMWcfDealServiceTestApp.ServiceReference1.Result UnwindSwapDeal(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.Unwind objUnwind);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISwapDealService/UnwindSwapDeal", ReplyAction="http://tempuri.org/ISwapDealService/UnwindSwapDealResponse")]
        System.Threading.Tasks.Task<QTMWcfDealServiceTestApp.ServiceReference1.Result> UnwindSwapDealAsync(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.Unwind objUnwind);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISwapDealServiceChannel : QTMWcfDealServiceTestApp.ServiceReference1.ISwapDealService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SwapDealServiceClient : System.ServiceModel.ClientBase<QTMWcfDealServiceTestApp.ServiceReference1.ISwapDealService>, QTMWcfDealServiceTestApp.ServiceReference1.ISwapDealService {
        
        public SwapDealServiceClient() {
        }
        
        public SwapDealServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SwapDealServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwapDealServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SwapDealServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QTMWcfDealServiceTestApp.ServiceReference1.QTMSession LogOn(string Username, string Password, string SiteName) {
            return base.Channel.LogOn(Username, Password, SiteName);
        }
        
        public System.Threading.Tasks.Task<QTMWcfDealServiceTestApp.ServiceReference1.QTMSession> LogOnAsync(string Username, string Password, string SiteName) {
            return base.Channel.LogOnAsync(Username, Password, SiteName);
        }
        
        public QTMWcfDealServiceTestApp.ServiceReference1.Result InitializeSwapDeal(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.SwapDeal objSwapDeal) {
            return base.Channel.InitializeSwapDeal(objQTMSession, objSwapDeal);
        }
        
        public System.Threading.Tasks.Task<QTMWcfDealServiceTestApp.ServiceReference1.Result> InitializeSwapDealAsync(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.SwapDeal objSwapDeal) {
            return base.Channel.InitializeSwapDealAsync(objQTMSession, objSwapDeal);
        }
        
        public QTMWcfDealServiceTestApp.ServiceReference1.Result CustomizeSwapDeal(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.Customize objCustomize) {
            return base.Channel.CustomizeSwapDeal(objQTMSession, objCustomize);
        }
        
        public System.Threading.Tasks.Task<QTMWcfDealServiceTestApp.ServiceReference1.Result> CustomizeSwapDealAsync(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.Customize objCustomize) {
            return base.Channel.CustomizeSwapDealAsync(objQTMSession, objCustomize);
        }
        
        public QTMWcfDealServiceTestApp.ServiceReference1.Result UnwindSwapDeal(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.Unwind objUnwind) {
            return base.Channel.UnwindSwapDeal(objQTMSession, objUnwind);
        }
        
        public System.Threading.Tasks.Task<QTMWcfDealServiceTestApp.ServiceReference1.Result> UnwindSwapDealAsync(QTMWcfDealServiceTestApp.ServiceReference1.QTMSession objQTMSession, QTMWcfDealServiceTestApp.ServiceReference1.Unwind objUnwind) {
            return base.Channel.UnwindSwapDealAsync(objQTMSession, objUnwind);
        }
    }
}
